### ISSUE TITLE
<v-grid> is rendered on top of <paper-drawer-panel>

### ISSUE THREAD

**Issue by tehapo** [vaadin/components#79]
When using &lt;paper-drawer-panel&gt; to provide a responsive layout, the &lt;v-grid&gt; component is rendered on top of the "background curtain".

![screen shot 2015-08-13 at 09 52 28](https://cloud.githubusercontent.com/assets/368220/9244332/ff0452b6-41a2-11e5-86f7-16174d6dc018.png)

Adding ```transform: translateZ(0);``` CSS rule to ```v-grid``` seems to be one possible solution.
![screen shot 2015-08-13 at 09 53 06](https://cloud.githubusercontent.com/assets/368220/9244367/3a87554a-41a3-11e5-9c0e-1a6996aa90aa.png)

**Comment by jounik** [comment]
Anything that creates a new stacking context for the main `v-grid` element should fix this issue.

I’m not sure if we can avoid the creation of a new rendering layer, perhaps with:

```css
position: relative;
z-index: 1;
```

**Comment by tehapo** [comment]
Applying that directly does not fix the issue, but changing the ```z-index``` to 0 seems to work.

```
position: relative;
z-index: 0;
```

**Comment by tomivirkki** [comment]
This could be done without affecting the main element by setting z-index: 0 to the actual grid (local dom) directly inside the v-grid element (it's already relative)

**Comment by jounik** [comment]
Right, that seems like the smallest change we can make.
